import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";

import type { Metadata } from "next";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Toaster
          toastOptions={{
            style: {
              boxShadow: "none",
              backgroundColor: "#FAFFEA",
              borderRadius: "16",
              maxWidth: "55ch",
              border: "1px solid #1c3a29",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
