export const ANIMATION_TIMELINE = [
  {
    top_cloud: 0,
    bottom_cloud: 0,
    dark_green_hill: 0,
    light_green_hill: 0,
    road_container: 0,
    main_bike: 0,
    broken_bike: 0,
    shocked_timmy: 0,
    crying_timmy: 0,
    grave: 0,
    polaroid: 0,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -362,
    broken_bike: -362,
    shocked_timmy: 146,
    crying_timmy: -361,
    grave: 0,
    polaroid: 0,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -362,
    broken_bike: -362,
    shocked_timmy: 146,
    crying_timmy: -361,
    grave: -296,
    polaroid: 0,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -362,
    broken_bike: -362,
    shocked_timmy: 146,
    crying_timmy: -361,
    grave: 0,
    polaroid: 0,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -402,
    broken_bike: -302,
    shocked_timmy: 86,
    crying_timmy: -281,
    grave: 0,
    polaroid: 0,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -402,
    broken_bike: -302,
    shocked_timmy: 86,
    crying_timmy: -281,
    grave: 0,
    polaroid: -326,
  },
  {
    top_cloud: -127,
    bottom_cloud: -120,
    dark_green_hill: -261,
    light_green_hill: -361,
    road_container: -362,
    main_bike: -402,
    broken_bike: -302,
    shocked_timmy: 86,
    crying_timmy: -281,
    grave: 0,
    polaroid: 0,
  },
];

export const TEXT_BOX = [
  {
    text: "1. Check your surroundings.",
    width: 314,
    height: 80,
    x: 0,
    y: 0,
  },
  {
    text: "2. Make sure everyone involved and around you is safe.",
    width: 314,
    height: 119,
    x: 0,
    y: -39,
  },
  {
    text: "3. If you are injured, call 911, your parents or guardian, and the parents or guardians of anyone else involved.",
    width: 314,
    height: 158,
    x: 108,
    y: -129,
  },
  {
    text: "4. If there is a neck/head injury, it is best to not move the person as this could worsen their injuries.",
    width: 314,
    height: 158,
    x: 0,
    y: -80,
  },
  {
    text: "5. If you can get up and move off the road, get into a safe location.",
    width: 314,
    height: 119,
    x: 0,
    y: -100,
  },
  {
    text: "6. Take a photo of the collision aftermath.",
    width: 314,
    height: 109,
    x: 140,
    y: -129,
  },
  {
    text: "7. Exchange contact information with the other party.",
    width: 314,
    height: 119,
    x: 0,
    y: -110,
  },
];
