name: Build and Commit Dist

on:
  push:
    branches:
      main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          fetch-depth: 0  # Ensures we get full history for commits

      - name: Install dependencies
        run: npm install

      # - name: Build project
      #   run: npm run build

      - name: Commit and push dist folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          HUSKY=0 git commit -m "Build: Update dist folder [skip ci]"
          git push origin main